# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed35baf0c702e00657426e1ae4a2180486bc227747e433f43276153ed3c43b80025001cf86ef893899e4882593c0484ffde0cf430efe83c006fc26e56620457c

test:
  secret_key_base: a372c6fcdb64a2cdc8fd049f0814cd146678a9fed087e7d31578e04724bbe0f78f363ff6bdcafbdfde780637261f0f935985859af881e0df0d7029fc5925ad61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
